### ISSUE TITLE
Example of .NET Memory Leak Needed

### ISSUE THREAD

**Issue by aodennison** [MartinKuschnik/WmiLight#3] opened 2017-06-13 13:36 UTC
An example of the assertion: "_The .Net framework implementation has one big problem. It leaks a little bit memory on each remote operation_." would be valuable for persuading my colleagues.

I did try a simple test (ManagementObject managementObject in searcher.Get()) with 1.8M iterations. I only saw only a small change in Peak Working Set and GC Total Memory.  What metrics should I be tracking?

**Comment by MartinKuschnik** [comment] 2017-06-13 13:47
It's hard to remember but it shout be more than a bit. Can you please share the whole code?

**Comment by aodennison** [comment] 2017-06-13 14:52
Hi,

Thanks for your response. I really do like idea of a simple WMI interface.
The .NET generated classes are particularly bloated. Although that is a
separate issue.


Below is the code I used. Running from within VS & AnyCPU may be incorrect,
and I am probably not monitoring the correct metrics. I would expect a
"leak" to escape the .NET metric, but I am not sure what I should watch. I
have not worked with memory profilers. I am hoping that a few pointers,
like: test standalone, Release config x86 and these metrics are all I need
to reproduce your findings, which of course I will share back to you/githib.

Thanks much,

Andy Dennison






using System;
using System.Diagnostics;
using System.Management;
using Handy.Common;

namespace WmiLeakExample
{
    static class Program
    {
        static int counter = 0;

        static void Main(string[] args)
        {
            DateTime stopTime = DateTime.Now + 6.Hours();
            counter = 0;

            while (DateTime.Now < stopTime)
            {
                ++counter;
                WmiLeakOne();
            }

            Debug.WriteLine($@"{counter} loops. Done.");

            Console.ReadKey();
        }

        static void WmiLeakOne()
        {
            using (ManagementObjectSearcher searcher = new
ManagementObjectSearcher(
                "SELECT Caption, ServicePackMajorVersion,
ServicePackMinorVersion,  Version, ProductType FROM Win32_OperatingSystem")
            )
            {
                // this is only expected to iterate once.
                foreach (ManagementObject managementObject in
searcher.Get())
                {
                    // adjust << 8 to see log entries more or less
frequently
                    if (counter % (1 << 8) == 0)
                    {
                        Process currentProcess =
Process.GetCurrentProcess(); // ensure fresh stats
                        Debug.WriteLine(
                            $@" {DateTime.Now}  {counter} loops, Peak
Working Set  {

currentProcess.PeakWorkingSet64.FormattedAsPowerOf1024(3)
                                }  GC Total Memory:
 {GC.GetTotalMemory(true).FormattedAsPowerOf1024(3)}");
                    }
                }
            }
        }
    }
}




Output
--------------------
 6/12/2017 7:08:55 PM  65536 loops, Peak Working Set  52.152 MiB  GC Total
Memory:  450.895 KiB
 6/12/2017 7:21:53 PM  131072 loops, Peak Working Set  52.355 MiB  GC Total
Memory:  456.156 KiB
 6/12/2017 7:34:45 PM  196608 loops, Peak Working Set  52.355 MiB  GC Total
Memory:  456.156 KiB
 6/12/2017 7:47:23 PM  262144 loops, Peak Working Set  52.355 MiB  GC Total
Memory:  456.156 KiB
 6/12/2017 8:00:16 PM  327680 loops, Peak Working Set  52.355 MiB  GC Total
Memory:  456.156 KiB
 6/12/2017 8:13:26 PM  393216 loops, Peak Working Set  52.355 MiB  GC Total
Memory:  456.156 KiB
 6/12/2017 8:25:58 PM  458752 loops, Peak Working Set  52.355 MiB  GC Total
Memory:  456.156 KiB
 6/12/2017 8:38:40 PM  524288 loops, Peak Working Set  52.355 MiB  GC Total
Memory:  456.156 KiB
 6/12/2017 8:51:29 PM  589824 loops, Peak Working Set  52.355 MiB  GC Total
Memory:  456.156 KiB
 6/12/2017 9:04:26 PM  655360 loops, Peak Working Set  52.355 MiB  GC Total
Memory:  456.156 KiB
 6/12/2017 9:17:37 PM  720896 loops, Peak Working Set  52.355 MiB  GC Total
Memory:  456.156 KiB
 6/12/2017 9:30:38 PM  786432 loops, Peak Working Set  52.355 MiB  GC Total
Memory:  456.156 KiB
 6/12/2017 9:43:36 PM  851968 loops, Peak Working Set  52.355 MiB  GC Total
Memory:  456.156 KiB
 6/12/2017 9:56:34 PM  917504 loops, Peak Working Set  52.355 MiB  GC Total
Memory:  456.156 KiB
 6/12/2017 10:09:27 PM  983040 loops, Peak Working Set  52.355 MiB  GC
Total Memory:  456.156 KiB
 6/12/2017 10:22:29 PM  1048576 loops, Peak Working Set  52.355 MiB  GC
Total Memory:  456.156 KiB
 6/12/2017 10:35:29 PM  1114112 loops, Peak Working Set  52.355 MiB  GC
Total Memory:  456.156 KiB
 6/12/2017 10:48:31 PM  1179648 loops, Peak Working Set  52.355 MiB  GC
Total Memory:  456.156 KiB
 6/12/2017 11:01:30 PM  1245184 loops, Peak Working Set  52.355 MiB  GC
Total Memory:  456.156 KiB
 6/12/2017 11:14:24 PM  1310720 loops, Peak Working Set  52.355 MiB  GC
Total Memory:  456.156 KiB
 6/12/2017 11:27:24 PM  1376256 loops, Peak Working Set  52.355 MiB  GC
Total Memory:  456.156 KiB
 6/12/2017 11:40:30 PM  1441792 loops, Peak Working Set  52.355 MiB  GC
Total Memory:  456.156 KiB
 6/12/2017 11:53:35 PM  1507328 loops, Peak Working Set  52.355 MiB  GC
Total Memory:  456.156 KiB
 6/13/2017 12:06:08 AM  1572864 loops, Peak Working Set  52.355 MiB  GC
Total Memory:  456.156 KiB
 6/13/2017 12:18:40 AM  1638400 loops, Peak Working Set  52.355 MiB  GC
Total Memory:  456.156 KiB
 6/13/2017 12:31:23 AM  1703936 loops, Peak Working Set  52.355 MiB  GC
Total Memory:  456.156 KiB
 6/13/2017 12:44:15 AM  1769472 loops, Peak Working Set  52.355 MiB  GC
Total Memory:  456.156 KiB
1830054 loops. Done.
The thread 0x6ff8 has exited with code 0 (0x0).
The thread 0x6244 has exited with code 0 (0x0).
The program '[38052] WmiLightExample.vshost.exe' has exited with code 0
(0x0).

**Comment by MartinKuschnik** [comment] 2017-06-13 15:09
*"The .Net framework implementation has one big problem. It leaks a little bit memory on each **remote** operation."*

Your code queries your local pc. Therefore you see no leak. But you can add a scope to the ManagmentObjectSearcher to query another pc.

**Comment by aodennison** [comment] 2017-06-13 15:15
Thanks for taking a look. Am I tracking the right metrics or are there
others that better show the issue?

**Comment by MartinKuschnik** [comment] 2017-06-13 15:21
Yes, this should work.

**Comment by aodennison** [comment] 2017-06-13 15:24
Thanks I will give it a go against a remote machine.

**Comment by MartinKuschnik** [comment] 2017-06-20 19:59
Did you tested it with remote connection?

**Comment by aodennison** [comment] 2017-06-20 20:01
No I have been fighting permissions issues and administrators. I will try
to get to it and let you know.

**Comment by MartinKuschnik** [comment] 2017-06-20 20:04
I know these problems :sweat:

**Comment by aodennison** [comment] 2017-06-21 03:49
Early tests do indeed show a slow leak on remote WMI calls. I am going to
add code to dedup the log, then let it run for overnight.



 6/20/2017 10:24:41 PM  1 loops, Peak Working Set 23.246 MiB  GC Total
Memory:  452.809 KiB
 6/20/2017 10:25:00 PM  93 loops, Peak Working Set 34.813 MiB  GC Total
Memory:  538.441 KiB
 6/20/2017 10:26:00 PM  393 loops, Peak Working Set 34.813 MiB  GC Total
Memory:  538.344 KiB
 6/20/2017 10:27:00 PM  696 loops, Peak Working Set 34.813 MiB  GC Total
Memory:  538.344 KiB
 6/20/2017 10:28:00 PM  989 loops, Peak Working Set 34.813 MiB  GC Total
Memory:  537.688 KiB
 6/20/2017 10:29:00 PM  1295 loops, Peak Working Set 34.813 MiB  GC Total
Memory:  537.066 KiB
 6/20/2017 10:30:00 PM  1592 loops, Peak Working Set 35.816 MiB  GC Total
Memory:  537.066 KiB
The thread 0x458c has exited with code 0 (0x0).
 6/20/2017 10:31:00 PM  1877 loops, Peak Working Set 35.816 MiB  GC Total
Memory:  537.637 KiB
 6/20/2017 10:32:00 PM  2173 loops, Peak Working Set 35.816 MiB  GC Total
Memory:  537.016 KiB
 6/20/2017 10:33:00 PM  2460 loops, Peak Working Set 35.816 MiB  GC Total
Memory:  537.016 KiB
 6/20/2017 10:34:00 PM  2759 loops, Peak Working Set 35.879 MiB  GC Total
Memory:  537.016 KiB
 6/20/2017 10:35:00 PM  3060 loops, Peak Working Set 36.004 MiB  GC Total
Memory:  537.016 KiB
 6/20/2017 10:36:00 PM  3360 loops, Peak Working Set 36.004 MiB  GC Total
Memory:  537.016 KiB
 6/20/2017 10:37:00 PM  3662 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  537.016 KiB
 6/20/2017 10:38:00 PM  3961 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  537.016 KiB
 6/20/2017 10:39:00 PM  4267 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  537.016 KiB
 6/20/2017 10:40:00 PM  4554 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  537.016 KiB
 6/20/2017 10:41:00 PM  4849 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  538.879 KiB
 6/20/2017 10:42:00 PM  5146 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  538.258 KiB
 6/20/2017 10:43:00 PM  5443 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  538.258 KiB
 6/20/2017 10:44:00 PM  5741 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  538.258 KiB
 6/20/2017 10:45:00 PM  6039 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  538.258 KiB
 6/20/2017 10:46:00 PM  6337 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  538.258 KiB
 6/20/2017 10:47:00 PM  6638 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  538.258 KiB
 6/20/2017 10:48:00 PM  6937 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  540.504 KiB
 6/20/2017 10:49:00 PM  7221 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  539.262 KiB
 6/20/2017 10:50:00 PM  7521 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  539.262 KiB
 6/20/2017 10:51:00 PM  7820 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  539.883 KiB
 6/20/2017 10:52:00 PM  8057 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  539.262 KiB
 6/20/2017 10:53:00 PM  8362 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  539.262 KiB
 6/20/2017 10:54:00 PM  8655 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  539.262 KiB
 6/20/2017 10:55:00 PM  8946 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  539.262 KiB
 6/20/2017 10:56:00 PM  9252 loops, Peak Working Set 36.852 MiB  GC Total
Memory:  539.262 KiB
 6/20/2017 10:57:00 PM  9560 loops, Peak Working Set 36.852 MiB  GC Total
Memory:  539.262 KiB
 6/20/2017 10:58:00 PM  9866 loops, Peak Working Set 36.852 MiB  GC Total
Memory:  539.262 KiB
 6/20/2017 10:59:00 PM  10177 loops, Peak Working Set 36.852 MiB  GC Total
Memory:  539.262 KiB
 6/20/2017 11:00:00 PM  10481 loops, Peak Working Set 36.875 MiB  GC Total
Memory:  539.262 KiB
 6/20/2017 11:01:00 PM  10780 loops, Peak Working Set 36.875 MiB  GC Total
Memory:  541.125 KiB
 6/20/2017 11:02:00 PM  11076 loops, Peak Working Set 36.875 MiB  GC Total
Memory:  541.125 KiB
 6/20/2017 11:03:00 PM  11374 loops, Peak Working Set 36.875 MiB  GC Total
Memory:  540.504 KiB
 6/20/2017 11:04:00 PM  11678 loops, Peak Working Set 36.875 MiB  GC Total
Memory:  540.504 KiB
 6/20/2017 11:05:00 PM  11979 loops, Peak Working Set 36.875 MiB  GC Total
Memory:  540.504 KiB
 6/20/2017 11:06:00 PM  12283 loops, Peak Working Set 36.875 MiB  GC Total
Memory:  540.539 KiB
 6/20/2017 11:07:00 PM  12576 loops, Peak Working Set 36.875 MiB  GC Total
Memory:  540.539 KiB
 6/20/2017 11:08:00 PM  12888 loops, Peak Working Set 36.875 MiB  GC Total
Memory:  540.539 KiB
 6/20/2017 11:09:00 PM  13202 loops, Peak Working Set 36.875 MiB  GC Total
Memory:  539.297 KiB
 6/20/2017 11:10:00 PM  13505 loops, Peak Working Set 36.875 MiB  GC Total
Memory:  539.262 KiB
 6/20/2017 11:11:00 PM  13814 loops, Peak Working Set 36.875 MiB  GC Total
Memory:  539.883 KiB
 6/20/2017 11:12:00 PM  14128 loops, Peak Working Set 36.875 MiB  GC Total
Memory:  539.883 KiB
 6/20/2017 11:13:00 PM  14442 loops, Peak Working Set 36.875 MiB  GC Total
Memory:  552.996 KiB
 6/20/2017 11:14:00 PM  14743 loops, Peak Working Set 36.875 MiB  GC Total
Memory:  552.996 KiB
 6/20/2017 11:15:00 PM  15052 loops, Peak Working Set 37.098 MiB  GC Total
Memory:  552.996 KiB
 6/20/2017 11:16:00 PM  15359 loops, Peak Working Set 37.098 MiB  GC Total
Memory:  552.996 KiB
 6/20/2017 11:17:00 PM  15664 loops, Peak Working Set 37.098 MiB  GC Total
Memory:  552.996 KiB
 6/20/2017 11:18:00 PM  15956 loops, Peak Working Set 37.098 MiB  GC Total
Memory:  552.996 KiB
 6/20/2017 11:19:00 PM  16270 loops, Peak Working Set 37.098 MiB  GC Total
Memory:  552.996 KiB
 6/20/2017 11:20:00 PM  16576 loops, Peak Working Set 37.098 MiB  GC Total
Memory:  552.996 KiB
 6/20/2017 11:21:00 PM  16875 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  554.238 KiB
 6/20/2017 11:22:00 PM  17171 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  554.859 KiB
 6/20/2017 11:23:00 PM  17463 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  554.238 KiB
 6/20/2017 11:24:00 PM  17747 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  554.238 KiB
 6/20/2017 11:25:00 PM  18046 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  554.238 KiB
 6/20/2017 11:26:00 PM  18347 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  554.238 KiB
 6/20/2017 11:27:00 PM  18652 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  554.238 KiB
 6/20/2017 11:28:00 PM  18956 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  554.238 KiB
 6/20/2017 11:29:00 PM  19260 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  554.238 KiB
 6/20/2017 11:30:00 PM  19566 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  553.012 KiB
 6/20/2017 11:31:00 PM  19874 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  553.012 KiB
 6/20/2017 11:32:00 PM  20182 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  553.617 KiB
 6/20/2017 11:33:00 PM  20484 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  553.012 KiB
 6/20/2017 11:34:00 PM  20788 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  553.012 KiB
 6/20/2017 11:35:00 PM  21082 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  553.012 KiB
 6/20/2017 11:36:00 PM  21383 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  553.012 KiB
 6/20/2017 11:37:00 PM  21689 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  553.012 KiB
 6/20/2017 11:38:00 PM  21979 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  553.012 KiB
 6/20/2017 11:39:00 PM  22289 loops, Peak Working Set 37.184 MiB  GC Total
Memory:  553.012 KiB
 6/20/2017 11:40:00 PM  22592 loops, Peak Working Set 37.199 MiB  GC Total
Memory:  553.012 KiB
 6/20/2017 11:41:00 PM  22890 loops, Peak Working Set 37.301 MiB  GC Total
Memory:  553.012 KiB
 6/20/2017 11:42:00 PM  23174 loops, Peak Working Set 37.301 MiB  GC Total
Memory:  554.859 KiB
 6/20/2017 11:43:00 PM  23476 loops, Peak Working Set 37.301 MiB  GC Total
Memory:  554.238 KiB
 6/20/2017 11:44:00 PM  23770 loops, Peak Working Set 37.301 MiB  GC Total
Memory:  554.238 KiB

**Comment by MartinKuschnik** [comment] 2017-06-21 08:36
That looks like the tiny leak i remember.
I also tried to reproduce the issue. But no success. Maybe its already fixed in the new .Net or windows version.

**Comment by aodennison** [comment] 2017-06-21 14:46
Now that I have a test program worth running more than once I can try it on
different versions/platforms. This log below was on VS2015  (debug mode)
.Net 4.5.2 on a Windows 7 box (the remote was WS 2016, but that is probably
not relevant)

Here is the cleaned up log. Note it is non-linear. It logs an entry when
the peak delta changes enough to be interesting:

 6/20/2017 11:58:52 PM  1 loops, Peak Working Set 23.230 MiB  GC Total
Memory:  442.418 KiB
 6/20/2017 11:58:52 PM  2 loops, Peak Working Set 25.250 MiB  GC Total
Memory:  527.988 KiB
 6/20/2017 11:58:53 PM  4 loops, Peak Working Set 26.457 MiB  GC Total
Memory:  527.988 KiB
 6/20/2017 11:58:53 PM  7 loops, Peak Working Set 27.996 MiB  GC Total
Memory:  527.988 KiB
 6/20/2017 11:58:54 PM  8 loops, Peak Working Set 28.434 MiB  GC Total
Memory:  527.988 KiB
 6/20/2017 11:58:54 PM  12 loops, Peak Working Set 29.531 MiB  GC Total
Memory:  527.988 KiB
 6/20/2017 11:58:55 PM  17 loops, Peak Working Set 30.082 MiB  GC Total
Memory:  527.988 KiB
 6/20/2017 11:58:58 PM  29 loops, Peak Working Set 31.387 MiB  GC Total
Memory:  527.988 KiB
 6/20/2017 11:59:02 PM  50 loops, Peak Working Set 32.215 MiB  GC Total
Memory:  527.988 KiB
 6/20/2017 11:59:07 PM  75 loops, Peak Working Set 33.262 MiB  GC Total
Memory:  527.988 KiB
 6/21/2017 12:00:59 AM  620 loops, Peak Working Set 34.098 MiB  GC Total
Memory:  528.023 KiB
 6/21/2017 12:01:52 AM  878 loops, Peak Working Set 35.176 MiB  GC Total
Memory:  529.836 KiB
 6/21/2017 12:49:54 AM  14853 loops, Peak Working Set 36.066 MiB  GC Total
Memory:  531.555 KiB
105171 loops. Done.


Thanks for pointing out that newer versions may be different.


On a related note, I spent too much time yesterday reverting code I had
changed away from using the "type-safe" generated classes back to ad hoc
queries (Select * from win32_..." . I have always felt these classes to be,
like much generated code, large clumsy code that you end up debugging.

In this case these are several generated classes that fail in a nasty way.
Where one class does the expected using the default constructor, 2 other
did not:
new Win32.OperatingSystem(0 -works as expected.

The type-safe classes for Win32_ComputerSystem, Win32_Processor fail when
using their default constructors.
Win32_ComputerSystem requires the computer name. E.g. new
Win32_ComputerSystem(Environment.MachineName)
Win32_Processor requires CPU0. E.g. new Win32_Processor("CPU0")


Another problem with the generated classes is that you need access to a
machine which supports the schema version and classes of interest. This
makes them impractical for automated builds. So we end up committing
generated source code.
I understand the rationale behind the self-describing schema, but I do
question its value.


Using your package is much lighter and usually the ad hoc query is all that
you need. Admittedly I only use the query functionality, and often only
need a string, but I think that is typical for many users of WMI.

**Comment by MartinKuschnik** [comment] 2017-06-21 15:26
But in your case there is a tiny leak. This is an problem if you implement a service that requests multiple servers and multiple classes every few seconds.

**Comment by aodennison** [comment] 2017-06-21 15:29
I agree completely. Even if the leak is tolerable in some cases, it is
worth knowing about. It makes debugging other leaks that much more
complicated.

**Comment by MartinKuschnik** [comment] 2017-06-21 15:41
You are right. Than I will close the issue.

**Closed by MartinKuschnik** 2017-06-21 15:41 UTC

**Comment by aodennison** [comment] 2017-06-21 15:43
Thanks for your help.
